origin: ohamadeh/linguist


# Define what permissions can be granted
statements:
  - subjects:
      - 'repo:${origin}:**' # any workflow from any branch
    permissions:
      contents: write  # Allow pushing
