name: octo-sts basic workflow
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read


jobs:
  test-job:
    runs-on: self-hosted
    steps:
      - uses: octo-sts/action@7a6ea3bef15ee86a65ffbaf678b6578a69a68610
        id: octo-sts
        with:
          scope: ohamadeh/argocd-example-apps
          identity: linguist

      - env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
        run: |
          gh repo list