name: qoomon basic workflow
on:
  workflow_dispatch:

permissions:
  id-token: write


jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: qoomon/actions--access-token@v3
        id: access-token
        with:
          owner: ohamadeh
          repository: linguist
          permissions: |
            contents: write
            pull-requests: write
      - env:
          GITHUB_TOKEN: ${{ steps.access-token.outputs.token }}
        run: |
          env  > env.txt
          gh repo list